DROP TABLE AU_AU_DA;
DROP TABLE AU_AU;
DROP TABLE PAYS_DA;
DROP TABLE PAYS_AU;
DROP TABLE MC_MC;
DROP TABLE PAYS_PAYS;
DROP TABLE MC_DA;
DROP TABLE TI_DA;
DROP TABLE ORGA_PAYS;
DROP TABLE ORGA_DA;
DROP TABLE ORGA_ORGA;
DROP TABLE ORGA_AU;
DROP TABLE AB_DA;


DROP TABLE AU;
DROP TABLE PAYS;
DROP TABLE DA;
DROP TABLE MC;
DROP TABLE ORGA;
DROP TABLE AB;
DROP TABLE TI;


CREATE TABLE AU(
		AU VARCHAR2(30),
		CONSTRAINT pk_AU PRIMARY KEY(AU));
		
CREATE TABLE TI(
		TI VARCHAR2(40),
		CONSTRAINT pk_TI PRIMARY KEY(TI));
		
CREATE TABLE AB (
		AB VARCHAR2(40),
		CONSTRAINT pk_AB PRIMARY KEY(AB));
		
CREATE TABLE PAYS (
		PAYS VARCHAR2(30),
		CONSTRAINT pk_PAYS PRIMARY KEY(PAYS));
		
CREATE TABLE DA (
		DA DATE,
		CONSTRAINT pk_DA PRIMARY KEY(DA));
		
CREATE TABLE MC (
		MC VARCHAR2(100),
		CONSTRAINT pk_MC PRIMARY KEY(MC));
		
CREATE TABLE ORGA (
		ORGA VARCHAR2(150),
		CONSTRAINT pk_ORGA PRIMARY KEY(ORGA));

CREATE TABLE AU_AU (
		idAU_AU NUMBER,
		AU1 VARCHAR2(30),
		AU2 VARCHAR2(30),
		occurences_AU_AU NUMBER,
		CONSTRAINT pk_idAU_AU PRIMARY KEY(idAU_AU),
		CONSTRAINT fk_au_au1 FOREIGN KEY(AU1) REFERENCES AU(AU),
		CONSTRAINT fk_au_au2 FOREIGN KEY(AU2) REFERENCES AU(AU));

CREATE TABLE PAYS_DA (
		idPAYS_DA NUMBER,
		PAYS VARCHAR2(30),
		DA_PD DATE,
		occurences_PAYS_DA NUMBER,
		CONSTRAINT pk_idPAYS_DA PRIMARY KEY(idPAYS_DA),
		CONSTRAINT fk_pays_da_pays FOREIGN KEY(PAYS) REFERENCES PAYS(PAYS),
		CONSTRAINT fk_pays_da_da FOREIGN KEY(DA_PD) REFERENCES DA(DA));

CREATE TABLE PAYS_AU (
		idPAYS_AU NUMBER,
		PAYS VARCHAR2(30),
		AU VARCHAR2(30),
		occurences_PAYS_AU NUMBER,
		CONSTRAINT pk_idPAYS_AU PRIMARY KEY(idPAYS_AU),
		CONSTRAINT fk_pays_AU_pays FOREIGN KEY(PAYS) REFERENCES PAYS(PAYS),
		CONSTRAINT fk_pays_AU_AU FOREIGN KEY(AU) REFERENCES AU(AU));		
		
CREATE TABLE MC_MC (
		idMC_MC NUMBER,
		MC1 VARCHAR2(100),
		MC2 VARCHAR2(100),
		occurences_MC_MC NUMBER,
		CONSTRAINT pk_idMC_MC PRIMARY KEY(idMC_MC),
		CONSTRAINT fk_mc_mc1 FOREIGN KEY(MC1) REFERENCES MC(MC),
		CONSTRAINT fk_mc_mc2 FOREIGN KEY(MC2) REFERENCES MC(MC));
		
CREATE TABLE PAYS_PAYS (
		idPAYS_PAYS NUMBER,
		PAYS1 VARCHAR2(30),
		PAYS2 VARCHAR2(30),
		occurences_PAYS_PAYS NUMBER,
		CONSTRAINT pk_idPAYS_PAYS PRIMARY KEY(idPAYS_PAYS),
		CONSTRAINT fk_pays_pays1 FOREIGN KEY(PAYS1) REFERENCES PAYS(PAYS),
		CONSTRAINT fk_pays_pays2 FOREIGN KEY(PAYS2) REFERENCES PAYS(PAYS));
		
CREATE TABLE AU_AU_DA (
		idAU_AU_DA NUMBER,
		AU1 VARCHAR2(30),
		AU2 VARCHAR2(30),
		DA_AAD DATE,
		occurences_AU_AU_DA NUMBER,
		CONSTRAINT pk_idAU_AU_DA PRIMARY KEY(idAU_AU_DA),
		CONSTRAINT fk_au_au1_da FOREIGN KEY(AU1) REFERENCES AU(AU),
		CONSTRAINT fk_au_au2_da FOREIGN KEY(AU2) REFERENCES AU(AU),
		CONSTRAINT fk_au_au_da FOREIGN KEY(DA_AAD) REFERENCES DA(DA));
		

		
		
CREATE TABLE MC_DA (
		idMC_DA  NUMBER,
		MC VARCHAR2(100),
		DA_MD DATE,
		occurences_MC_DA NUMBER,
		CONSTRAINT pk_idMC_DA PRIMARY KEY(idMC_DA),
		CONSTRAINT fk_mc_da_mc FOREIGN KEY(MC) REFERENCES MC(MC),
		CONSTRAINT fk_mc_da_da FOREIGN KEY(DA_MD) REFERENCES DA(DA));

CREATE TABLE TI_DA (
		idTI_DA  NUMBER,
		TI VARCHAR2(40),
		DA_TD DATE,
		occurences_TI_DA NUMBER,
		CONSTRAINT pk_idTI_DA PRIMARY KEY(idTI_DA),
		CONSTRAINT fk_ti_da_ti FOREIGN KEY(TI) REFERENCES TI(TI),
		CONSTRAINT fkti_da_da FOREIGN KEY(DA_TD) REFERENCES DA(DA));
		
CREATE TABLE ORGA_DA (
		idORGA_DA  NUMBER,
		ORGA VARCHAR2(150),
		DA_OD DATE,
		occurences_ORGA_DA NUMBER,
		CONSTRAINT pk_idORGA_DA PRIMARY KEY(idORGA_DA),
		CONSTRAINT fk_orga_da_orga FOREIGN KEY(ORGA) REFERENCES ORGA(ORGA),
		CONSTRAINT fk_orga_da_da FOREIGN KEY(DA_OD) REFERENCES DA(DA));
		
CREATE TABLE ORGA_PAYS (
		idORGA_PAYS  NUMBER,
		ORGA VARCHAR2(150),
		PAYS VARCHAR2(30),
		occurences_ORGA_PAYS NUMBER,
		CONSTRAINT pk_idORGA_PAYS PRIMARY KEY(idORGA_PAYS),
		CONSTRAINT fk_orga_pays_orga FOREIGN KEY(ORGA) REFERENCES ORGA(ORGA),
		CONSTRAINT fk_orga_pays_pays FOREIGN KEY(PAYS) REFERENCES PAYS(PAYS));		
		
CREATE TABLE ORGA_AU (
		idORGA_AU  NUMBER,
		ORGA VARCHAR2(150),
		AU VARCHAR2(30),
		occurences_ORGA_AU NUMBER,
		CONSTRAINT pk_idORGA_AU PRIMARY KEY(idORGA_AU),
		CONSTRAINT fk_orga_au_orga FOREIGN KEY(ORGA) REFERENCES ORGA(ORGA),
		CONSTRAINT fk_orga_au_au FOREIGN KEY(AU) REFERENCES AU(AU));		
		
CREATE TABLE AB_DA (
		idAB_DA  NUMBER,
		AB VARCHAR2(40),
		DA_AD DATE,
		occurences_AB_DA NUMBER,
		CONSTRAINT pk_idAB_DA PRIMARY KEY(idAB_DA),
		CONSTRAINT fk_ab_da_ab FOREIGN KEY(AB) REFERENCES AB(AB),
		CONSTRAINT fk_ab_da_da FOREIGN KEY(DA_AD) REFERENCES DA(DA));		
	
CREATE TABLE ORGA_ORGA (
		idORGA_ORGA  NUMBER,
		ORGA1 VARCHAR2(150),
		ORGA2 VARCHAR2(150),
		occurences_ORGA_ORGA NUMBER,
		CONSTRAINT pk_idORGA_ORGA PRIMARY KEY(idORGA_ORGA),
		CONSTRAINT fk_orga_orga1 FOREIGN KEY(ORGA1) REFERENCES ORGA(ORGA),
		CONSTRAINT fk_orga_orga2 FOREIGN KEY(ORGA2) REFERENCES ORGA(ORGA);				