DROP TABLE AU_AU;
DROP TABLE PAYS_DA;
DROP TABLE MC_MC;
DROP TABLE PAYS_PAYS;

DROP TABLE AU;
DROP TABLE PAYS;
DROP TABLE DA;
DROP TABLE MC;
DROP TABLE ORGA;
DROP TABLE AB;
DROP TABLE TI;


CREATE TABLE AU(
		AU VARCHAR2(30) PRIMARY KEY);
		
CREATE TABLE TI(
		TI VARCHAR2(80) PRIMARY KEY);
		
CREATE TABLE AB (
		AB VARCHAR2(160) PRIMARY KEY);
		
CREATE TABLE PAYS (
		PAYS VARCHAR2(20) PRIMARY KEY);
		
CREATE TABLE DA (
		date DATE PRIMARY KEY);
		
CREATE TABLE MC (
		MC VARCHAR2(30) PRIMARY KEY);
		
CREATE TABLE ORGA (
		ORGA VARCHAR2(30) PRIMARY KEY);

CREATE TABLE AU_AU (
		idAU_AU NUMBER PRIMARY KEY,
		AU1 VARCHAR(30),
		AU2 VARCHAR(30),
		occurences NUMBER,
		CONSTRAINT fk_au_au1 FOREIGN KEY AU1 REFERENCES AU(AU),
		CONSTRAINT fk_au_au2 FOREIGN KEY AU2 REFERENCES AU(AU));

CREATE TABLE PAYS_DA (
		idPAYS_DA NUMBER PRIMARY KEY,
		PAYS VARCHAR(30),
		DA VARCHAR(30),
		occurences NUMBER);

CREATE TABLE MC_MC (
		idMC_MC NUMBER PRIMARY KEY,
		MC1 VARCHAR(30),
		MC2 VARCHAR(30),
		occurences NUMBER);
		
CREATE TABLE PAYS_PAYS (
		idPAYS_PAYS NUMBER PRIMARY KEY,
		PAYS1 VARCHAR(30),
		pays2 VARCHAR(30),
		occurences NUMBER);