DROP TABLE AU_AU_DA;
DROP TABLE AU_AU;
DROP TABLE PAYS_DA;
DROP TABLE PAYS_AU;
DROP TABLE MC_MC;
DROP TABLE PAYS_PAYS;

DROP TABLE AU;
DROP TABLE PAYS;
DROP TABLE DA;
DROP TABLE MC;
DROP TABLE ORGA;
DROP TABLE AB;
DROP TABLE TI;


CREATE TABLE AU(
		AU VARCHAR2(30),
		CONSTRAINT pk_AU PRIMARY KEY(AU));
		
CREATE TABLE TI(
		TI VARCHAR2(80),
		CONSTRAINT pk_TI PRIMARY KEY(TI));
		
CREATE TABLE AB (
		AB VARCHAR2(160),
		CONSTRAINT pk_AB PRIMARY KEY(AB));
		
CREATE TABLE PAYS (
		PAYS VARCHAR2(30),
		CONSTRAINT pk_PAYS PRIMARY KEY(PAYS));
		
CREATE TABLE DA (
		DA DATE,
		CONSTRAINT pk_DA PRIMARY KEY(DA));
		
CREATE TABLE MC (
		MC VARCHAR2(30),
		CONSTRAINT pk_MC PRIMARY KEY(MC));
		
CREATE TABLE ORGA (
		ORGA VARCHAR2(30),
		CONSTRAINT pk_ORGA PRIMARY KEY(ORGA));

CREATE TABLE AU_AU (
		idAU_AU NUMBER,
		AU1 VARCHAR2(30),
		AU2 VARCHAR2(30),
		occurences_AU_AU NUMBER,
		CONSTRAINT pk_idAU_AU PRIMARY KEY(idAU_AU),
		CONSTRAINT fk_au_au1 FOREIGN KEY(AU1) REFERENCES AU(AU),
		CONSTRAINT fk_au_au2 FOREIGN KEY(AU2) REFERENCES AU(AU));

CREATE TABLE PAYS_DA (
		idPAYS_DA NUMBER,
		PAYS VARCHAR2(30),
		DA_PD DATE,
		occurences_PAYS_DA NUMBER,
		CONSTRAINT pk_idPAYS_DA PRIMARY KEY(idPAYS_DA),
		CONSTRAINT fk_pays_da_pays FOREIGN KEY(PAYS) REFERENCES PAYS(PAYS),
		CONSTRAINT fk_pays_da_da FOREIGN KEY(DA_PD) REFERENCES DA(DA));

CREATE TABLE PAYS_AU (
		idPAYS_AU NUMBER,
		PAYS VARCHAR2(30),
		AU VARCHAR2(30),
		occurences_PAYS_AU NUMBER,
		CONSTRAINT pk_idPAYS_AU PRIMARY KEY(idPAYS_AU),
		CONSTRAINT fk_pays_AU_pays FOREIGN KEY(PAYS) REFERENCES PAYS(PAYS),
		CONSTRAINT fk_pays_AU_AU FOREIGN KEY(AU) REFERENCES AU(AU));		
		
CREATE TABLE MC_MC (
		idMC_MC NUMBER,
		MC1 VARCHAR2(30),
		MC2 VARCHAR2(30),
		occurences_MC_MC NUMBER,
		CONSTRAINT pk_idMC_MC PRIMARY KEY(idMC_MC),
		CONSTRAINT fk_mc_mc1 FOREIGN KEY(MC1) REFERENCES MC(MC),
		CONSTRAINT fk_mc_mc2 FOREIGN KEY(MC2) REFERENCES MC(MC));
		
CREATE TABLE PAYS_PAYS (
		idPAYS_PAYS NUMBER,
		PAYS1 VARCHAR2(30),
		PAYS2 VARCHAR2(30),
		occurences_PAYS_PAYS NUMBER,
		CONSTRAINT pk_idPAYS_PAYS PRIMARY KEY(idPAYS_PAYS),
		CONSTRAINT fk_pays_pays1 FOREIGN KEY(PAYS1) REFERENCES PAYS(PAYS),
		CONSTRAINT fk_pays_pays2 FOREIGN KEY(PAYS2) REFERENCES PAYS(PAYS));
		
CREATE TABLE AU_AU_DA (
		idAU_AU_DA NUMBER,
		AU1 VARCHAR2(30),
		AU2 VARCHAR2(30),
		DA_AAD DATE,
		occurences_AU_AU_DA NUMBER,
		CONSTRAINT pk_idAU_AU_DA PRIMARY KEY(idAU_AU_DA),
		CONSTRAINT fk_au_au1_da FOREIGN KEY(AU1) REFERENCES AU(AU),
		CONSTRAINT fk_au_au2_da FOREIGN KEY(AU2) REFERENCES AU(AU),
		CONSTRAINT fk_au_au_da FOREIGN KEY(DA_AAD) REFERENCES DA(DA));